apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubescape
  namespace: ks-scanner
  labels:
    app: kubescape
spec:
  selector:
    matchLabels:
      app: kubescape
  podMetricsEndpoints:
  - port: http
    # path: v1
    interval: 120s
    scrapeTimeout: 100s
