name: c-create_release
on:
  workflow_call:
    inputs:
      RELEASE_NAME:
        description: 'Release name'
        required: true
        type: string
      TAG:
        description: 'Tag name'
        required: true
        type: string
      DRAFT:
        description: 'Create draft release'
        required: false
        type: boolean
        default: false

jobs:

  create-release:
    name: create-release
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write    
    steps:
      - uses: actions/download-artifact@v3.0.2
        id: download-artifact
        with:
          path: .

      # - name: artifacts rename
      #   env:
      #     MAC_OS: macos-latest
      #     UBUNTU_OS: ubuntu-latest
      #     WINDOWS_OS: windows-latest
      #   run: |

      #     mv ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }} ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}-${{ inputs.TAG }}
      #     mv ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}.sha256 ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}-${{ inputs.TAG }}.sha256
      #     mv ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}.tar.gz ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}-${{ inputs.TAG }}.tar.gz

      #     mv ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }} ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}-${{ inputs.TAG }}
      #     mv ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}.sha256 ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}-${{ inputs.TAG }}.sha256
      #     mv ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}.tar.gz ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}-${{ inputs.TAG }}.tar.gz

      #     mv ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }} ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}-${{ inputs.TAG }}
      #     mv ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}.sha256 ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}-${{ inputs.TAG }}.sha256
      #     mv ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}.tar.gz ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}-${{ inputs.TAG }}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          MAC_OS: macos-latest
          UBUNTU_OS: ubuntu-latest
          WINDOWS_OS: windows-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.RELEASE_NAME }}
          tag_name: ${{ inputs.TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: ${{ inputs.DRAFT }}
          fail_on_unmatched_files: true
          prerelease: false
          files: |
            ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}
            ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}.sha256
            ./kubescape-${{ env.MAC_OS }}/kubescape-${{ env.MAC_OS }}.tar.gz
            ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}
            ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}.sha256
            ./kubescape-${{ env.UBUNTU_OS }}/kubescape-${{ env.UBUNTU_OS }}.tar.gz
            ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}
            ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}.sha256
            ./kubescape-${{ env.WINDOWS_OS }}/kubescape-${{ env.WINDOWS_OS }}.tar.gz
 
            
