name: c-create_release
permissions: read-all
on:
  workflow_call:
    inputs:
      RELEASE_NAME:
        description: 'Release name'
        required: true
        type: string
      TAG:
        description: 'Tag name'
        required: true
        type: string
      DRAFT:
        description: 'Create draft release'
        required: false
        type: boolean
        default: false
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    env:
      MAC_OS: macos-latest
      UBUNTU_OS: ubuntu-latest
      WINDOWS_OS: windows-latest
    # permissions:
    #   contents: write
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # ratchet:actions/download-artifact@v3.0.2
        id: download-artifact
        with:
          path: .

      # TODO: kubescape-windows-latest is deprecated and should be removed
      - name: Get kubescape.exe from kubescape-windows-latest
        run: cp ${{steps.download-artifact.outputs.download-path}}/kubescape-${{ env.WINDOWS_OS }} ${{steps.download-artifact.outputs.download-path}}/kubescape.exe

      - name: Set release token
        run: |
          if [ "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" != "" ]; then
            echo "TOKEN=${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" >> $GITHUB_ENV;
          else
            echo "TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV;
          fi

      - name: Generate file list
        id: generate-file-list
        run: |
          FILES=$(find ${{steps.download-artifact.outputs.download-path}} -type f | sed 's/^/.\//')
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # ratchet:softprops/action-gh-release@v1
        with:
          token: ${{ env.TOKEN }}
          name: ${{ inputs.RELEASE_NAME }}
          tag_name: ${{ inputs.TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: ${{ inputs.DRAFT }}
          fail_on_unmatched_files: true
          prerelease: false
          files: ${{ env.FILES }}
