name: pr-checks

on:
  pull_request:
    branches: [ master, dev ]
    types: [ edited, opened, synchronize, reopened ]
    paths-ignore:
      # Do not run the pipeline if only Markdown files changed
      - '**.yaml'
      - '**.md'
  push:
    branches: [ workflow-call-testing ]
jobs:
  trigger-test-workflow:
    uses: ./.github/workflows/test.yaml
    with:
      release: "v2.0.${{ github.run_number }}"
      client: test
